In [ ]:
#AISHWARYA GANDHI.M
#AMB2011

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])

7


create a 2-D array i.e 2*5,Acess the 2nd element on first dimension

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st dim:',arr[0,1])
print('5th element on 1st dim:',arr[1,4])

2nd element on 1st dim: 2
5th element on 1st dim: 10


In [ ]:
#acess the third element of the secord array of the first arrary
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
print()
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]

6


In [ ]:
#python program to perform basic arthematic operation using 1-D array
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
diff=arr[3]-arr[2]
product=arr[1]*arr[3]
div=arr[4]/arr[1]
print(sum)
print(diff)
print(product)
print(div)

6
2
21
3.0


In [ ]:
#Slicing 1D array
import numpy as np
arr=np.array([2,4,6,8,10,12,14,16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]
